project:
  type: website

title: "RoadMap"
author: "Boris Ivan Huarachi Perez"

website:
  title: "RoadMap"
  navbar:
    left:
      - text: "DevOps"
        menu:
          - text: "Roadmap"
            href: index.qmd
      - text: "Cloud Architect"
        menu:
          - text: "Cloud Architect"
            href: arqui.qmd
    right:
      - icon: github
        href: "https://github.com/borizSam"
        aria-label: "GitHub"

  page-footer:
    center:
      - text: "© 2024 RoadMap · Creado por Boris Ivan Huarachi Perez"
        href: "#"

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true
    code-copy: true
    code-overflow: wrap

metadata:
  lang: es
  author: "Boris Ivan Huarachi Perez"

extra-css:
  - "https://fonts.googleapis.com/css2?family=Roboto:wght@400;500&family=Montserrat:wght@700&display=swap"

resources:
  - styles.css

# Scripts externos (opcional si los usas activamente)
extra-scripts:
  - "https://kit.fontawesome.com/a076d05399.js"
  - "https://cdn.jsdelivr.net/npm/sweetalert2@11"

# Accesibilidad
accessibility:
  skip_to_content: true
  contrast_mode: true
